# tasks for fedora-messaging setup
---

- import_role:
    name: fedora-messaging-client
  vars:
    fedora_messaging_tls_certs: True
    fedora_messaging_tls_cert: "{{ robosignatory_fedora_messaging_cert }}"
    fedora_messaging_tls_key: "{{ robosignatory_fedora_messaging_key }}"
    fedora_messaging_tls_ca: "{{ robosignatory_fedora_messaging_ca }}"

- name: Setup robosignatory config
  template:
    src: fedora-messaging/robosignatory.toml.j2
    dest: /etc/fedora-messaging/robosignatory.toml
    owner: robosignatory
    group: robosignatory
    mode: 0640
  tags:
    - config
  notify:
    - restart robosignatory

- name: Create /etc/systemd/system/fm-consumer@.service.d
  file:
    state: directory
    path: /etc/systemd/system/fm-consumer@.service.d
    owner: root
    group: root
    mode: 0755

- name: Configure fm-consumer@.service to run as robosignatory
  copy:
    src: robosignatory/fm-consumer@.service
    dest: /etc/systemd/system/fm-consumer@.service.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - reload_systemd

- name: Ensure robosignatory service is enabled and started
  service:
    name: fm-consumer@robosignatory.service
    enabled: yes
    state: started
