# tasks for role robosignatory setup
---
- name: Install robosignatory packages
  yum:
    name: "{{ robosignatory_pkgs }}"
    state: latest
  tags:
    - pkgs
    - gssproxy

- name: Ensure group "robosignatory" exists
  group:
    name: robosignatory
    state: present
    system: yes
    # gid: XXX

- name: Ensure user "robosignatory" exists
  user:
    name: robosignatory
    group: robosignatory
    system: yes
    home: /etc/robosignatory
    comment: robosignatory
    shell: /sbin/nologin
    # uid: XXX

- name: Ensure config directory /etc/robosignatory/ exists
  file:
    path: /etc/robosignatory/
    state: directory
    owner: robosignatory
    group: robosignatory
    mode: 0750

- name: Install koji config
  template:
    src: robosignatory/koji.config.j2
    dest: /etc/robosignatory/koji.config
    owner: robosignatory
    group: robosignatory
    mode: 0640
  tags:
    - koji

- name: Copy koji keytab
  copy:
    src: "{{ robosignatory_pki_store }}/krb5/{{ robosignatory_config_krb_keytab }}"
    dest: /etc/robosignatory/{{ robosignatory_config_krb_keytab }}
    owner: robosignatory
    group: robosignatory
    mode: 0640
  when: robosignatory_kojihub_auth_type == 'kerberos'
  tags:
    - koji

- name: Allow robosignatory to use systemd-ask-password
  copy:
    src: robosignatory/ask-password-robosignatory.conf
    dest: /etc/tmpfiles.d/ask-password-robosignatory.conf
    owner: root
    group: root
    mode: 0644

- name: Adding some helper scripts
  copy:
    src: "robosignatory/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - sign_stream_repodata.sh
  tags:
    - scripts

- block:
    - name: Configuring gssproxy
      template:
        src: gssproxy/20-rpmsign.conf.j2 
        dest: /etc/gssproxy/20-rpmsign.conf
        owner: root
        group: root
        mode: 0600
      notify:
        - restart_gssproxy

    - name: Ensuring gssproxy is started
      service:
        name: gssproxy
        state: started
        enabled: True
    
    - name: Systemd snippet directory
      file:
        path: /etc/systemd/system/fm-consumer@.service.d/
        state: directory

    - name: Configuring robosignatory environment for gssproxy
      template:
        src: systemd-robosignatory.conf.j2
        dest: /etc/systemd/system/fm-consumer@.service.d/override.conf
        mode: 0644
      register: robosignatory_systemd_override
      notify:
        - restart robosignatory

    - name: Reloading systemd if needed
      systemd:
        daemon-reload: yes
      when: robosignatory_systemd_override is changed

      
  tags:
    - gssproxy


- block:
    - name: Adding robosignatory delegated users (scripts)
      user:
        name: "{{ item.name }}"
        state: present
        shell: "{{ item.shell | default('/bin/bash') }}"
        uid: "{{ item.uid }}"
      with_items: "{{ robosignatory_delegated_users }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: Adding ssh pub keys for delegated users
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1 }}"
      with_subelements:
        - "{{ robosignatory_delegated_users }}"
        - authorized_keys
      loop_control:
        label: "{{ item.0.name }}"
    - name: Granting gssproxy access if needed
      template:
        src: gssproxy/21-rpmsign-user.conf.j2
        dest: "/etc/gssproxy/21-rpmsign-{{ item.name }}.conf"
        owner: root
        group: root
        mode: 0600
      with_items: "{{ robosignatory_delegated_users }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.gssproxy_enabled    
      notify:   
        - restart_gssproxy
  tags:
    - users
