# tasks for role robosignatory setup
---
- name: Install robosignatory packages
  yum:
    name:
      - python3-robosignatory
      - trousers
      - tpm-tools
      - gssproxy
    state: latest
  tags:
    - pkgs
    - gssproxy

- name: Ensure group "robosignatory" exists
  group:
    name: robosignatory
    state: present
    system: yes
    # gid: XXX

- name: Ensure user "robosignatory" exists
  user:
    name: robosignatory
    group: robosignatory
    system: yes
    home: /etc/robosignatory
    comment: robosignatory
    shell: /sbin/nologin
    # uid: XXX

- name: Ensure config directory /etc/robosignatory/ exists
  file:
    path: /etc/robosignatory/
    state: directory
    owner: robosignatory
    group: robosignatory
    mode: 0750

- name: Install koji config
  template:
    src: robosignatory/koji.config.j2
    dest: /etc/robosignatory/koji.config
    owner: robosignatory
    group: robosignatory
    mode: 0640
  tags:
    - koji

- name: Copy koji keytab
  copy:
    src: "{{ robosignatory_pki_store }}/krb5/{{ robosignatory_config_krb_keytab }}"
    dest: /etc/robosignatory/{{ robosignatory_config_krb_keytab }}
    owner: robosignatory
    group: robosignatory
    mode: 0640
  when: robosignatory_kojihub_auth_type == 'kerberos'

- name: Install koji CA certificate
  copy:
    src: "{{ robosignatory_pki_store }}/koji/{{ robosignatory_kojid_serverca }}"
    dest: /etc/robosignatory/serverca.cert
    owner: robosignatory
    group: robosignatory
    mode: 0640

- name: Allow robosignatory to use systemd-ask-password
  copy:
    src: robosignatory/ask-password-robosignatory.conf
    dest: /etc/tmpfiles.d/ask-password-robosignatory.conf
    owner: root
    group: root
    mode: 0644

- block:
    - name: Configuring gssproxy
      template:
        src: gssproxy/20-rpmsign.conf.j2 
        dest: /etc/gssproxy/20-rpmsign.conf
        owner: root
        group: root
        mode: 0600
      notify:
        - restart_gssproxy

    - name: Ensuring gssproxy is started
      service:
        name: gssproxy
        state: started
        enabled: True
    
    - name: Systemd snippet directory
      file:
        path: /etc/systemd/system/fm-consumer@.service.d/
        state: directory

    - name: Configuring robosignatory environment for gssproxy
      template:
        src: systemd-robosignatory.conf.j2
        dest: /etc/systemd/system/fm-consumer@.service.d/override.conf
        mode: 0644
      register: robosignatory_systemd_override
      notify:
        - restart robosignatory

    - name: Reloading systemd if needed
      systemd:
        daemon-reload: yes
      when: robosignatory_systemd_override is changed

      
  tags:
    - gssproxy
