---
# handlers file for ansible-role-robosignatory
- name: reload_systemd
  systemd:
    daemon_reload: yes

- name: restart robosignatory
  service:
    name: fm-consumer@robosignatory.service
    state: restarted

